add display entities, update links, removed clentaminator
Moulberry/AxiomDocumentation pull request #22
Opened 2024-05-25 22:14 UTC by WILLATRONIX

2024-05-29 15:27 UTC, TheWarior73 commented
Hi, I have noticed some broken links in the current V of the docs, and found your PR, just to make sure that the links are working as intended, let's take an example :
When in `src/advanced/configuration.md` you link the `Blueprints` using the following link :
```md
The folders are used to store saved [Blueprints](/editor/blueprints.md), ...........
```
Will it link properly when built ? since you are starting from the `root/editor/...` there is a problem with viewing it from the GitHub.
Just wanted to make sure 👍  

Aline aka Th3_Warior

2024-05-29 15:40 UTC, WILLATRONIX commented
> Hi, I have noticed some broken links in the current V of the docs, and found your PR, just to make sure that the links are working as intended, let's take an example : When in `src/advanced/configuration.md` you link the `Blueprints` using the following link :
> 
> ```
> The folders are used to store saved [Blueprints](/editor/blueprints.md), ...........
> ```
> 
> Will it link properly when built ? since you are starting from the `root/editor/...` there is a problem with viewing it from the GitHub. Just wanted to make sure 👍
> 
> Aline aka Th3_Warior

2024-05-29 15:44 UTC, WILLATRONIX commented
@TheWarior73  yes, [the config links](https://github.com/Moulberry/AxiomDocumentation/pull/22/commits/0afa4d54c6241275bc9647f01a3bdd55e637cffe) and [all other links](https://github.com/Moulberry/AxiomDocumentation/pull/22/commits/24a9bda91e0d416d31966f38a618d2bea7cc5892) were fixed in this pr

2024-05-29 15:48 UTC, TheWarior73 commented
@WILLATRONIX I saw your PR commits don't worry, I am not the type to comment for nothing...
I was actually wondering if the build would get the links incorrectly or not, since on the repo you cannot navigate using them (dut to the link not using SRC.
I will assume that it won't be a problem 👍 

Thank you for the answer

2024-06-03 19:40 UTC, Moulberry requested changes

2024-06-03 19:40 UTC, Moulberry commented on src/advanced/commands.md
> +- Used to check whether the player has the provided [permission](/multiplayer/permissions.md) and returns true/false.
This isn't what the /axiompaperdebug command does

2024-06-03 19:40 UTC, Moulberry commented on src/builder/blockattributes.md
> +| Show Collision Mesh          | Creates a red outline for every block with a transparent hitbox like leaves or fences.     |
Barriers are the main reason you'd use this, might be good to mention

2024-06-03 19:40 UTC, Moulberry commented on src/builder/blockattributes.md
> +[^note2]: ![Light Block Texture](/img/structure_void.png)
Wrong name, should be structure void texture

2024-06-03 19:40 UTC, Moulberry commented on src/editor/windows/blueprints.md
> +Blueprints are stored as `.bp` files in the [Configuration](/advanced/configuration.md). The blueprint file itself is a GZ[^note1] and can be opened in programs such as 7zip to reveal the NBT file in
This is not how blueprint files are stored

2024-06-03 19:40 UTC, Moulberry commented on src/intro.md
> +## Latest Update
Probably shouldn't have latest update here as it'd require constant maintenance to keep updated. People can look at the changelogs on modrinth/the website anyways if they want this information

2024-06-03 19:40 UTC, Moulberry commented on src/multiplayer/commercial.md
> +# Commercial Usage
Please remove this page, I think it'll just cause more confusion

2024-06-03 19:40 UTC, Moulberry commented on src/multiplayer/intro.md
> +If you're using Axiom for commercial purposes, you'll need to purchase a [Commercial License](commercial.md).
Change this to link directly to commercial license page

2024-06-03 19:40 UTC, Moulberry commented on src/advanced/commands.md
> +These are some extra commands for controlling the world and its properties. These are not available in [Multiplayer](/multiplayer/intro.md).
Only available on Fabric, not Paper

2024-06-03 19:54 UTC, Moulberry approved these changes

2024-06-03 19:54 UTC, merged